### PR TITLE
feat: added WaspLib's mainscreen polygons.

### PR DESCRIPTION
**Pull request by Torwent**
Credits actually go to @ollydev  for helping me figuring out how to properly join the rectangles.

Also renamed `TRSWalker.GetTileMSEx` to `TRSWalker.GetTileMS` and made the original an overloaded method.

### CODE REVIEW

**Comment by slackydev** [comment]
Isn't this a little bloating?
Basically what you want to achieve with this is to avoid two calls, one for top, and one for bottom? Which is in fact more adaptable, given that it can work at different heights for both bottom and top.

I added some basic methods relating to this long ago, as I expected that to be the way we do it
> `procedure TMufasaBitmap.DrawCuboid(Top, Btm: TRectangle; Color: Int32); constref;`
> `function TSRL.PointInCuboid(pt: TPoint; Top, Btm: TRectangle): Boolean; static;`

which just extends on using two rectangle, top, bottom. I would have thought that was simple enough.

> `(RSW.GetTileMS(..).ToTPA + RSW.GetTileMS(..).ToTPA).ConvexHull()`

-----

I also chose to use `GetTileMSEx` as a name since it's __not__ the same method just for another type, and I wanted to make that clear. overloads are good, but they go best with methods that are equal just for different types.


-----

Perhaps a better solution is to add a type `TCuboid = record Top, Bottom: TRect; end;` which can hold a few methods that makes it simpler? Would still need some more calls to MM2MS-projection. But your solution seems a bit much to add, for so little gain.

**Comment by Torwent** [comment]
Hummm yeah it can be made separately but you do a lot of lines if you want to do this a lot (I personally do... I use MS Cuboids for everything except item drops).

But that's okay, I just thought it would be useful for everyone hehe.

As for `GetTileMSEx`, I know you named it differently on purposed but I was trying to streamline it with others things in SRL.
I understand the logic of what you are saying but SRL has loads of examples of what I just did there, look at `Inventory.FindItem` for example.
Maybe the issue is that they are both called `FindItem` and should have totally different names like `ContainsItem` and `FindItem`.

as for the `TCuboid` I like it. Maybe it doesn't even need to be in SRL but I like it because that's much cleaner than what I have in WaspLib.

I'll close this PR, thanks for the feedback!

**Comment by slackydev** [comment]
Yeah that one FindItem is wrongly named, and I will go ahead and change that. That's definitely a ContainsItem-kind of method. And sure there will be bad examples of overloads in SRL. As well as good ones. Let's learn from the good ones, and ignore the bad ones.

**Comment by Torwent** [comment]
There's also more cases like that, but none from the top of my head right now.
Inventory has a couple of them, probably bank too.

**Comment by Torwent** [comment]
oops... reopened the PR by accident lol

**Pull request closed without merging**
