### PR TITLE
a couple more fixes and changes. mouse.simba needs to be reviewed

### PR DESCRIPTION
**Pull request by Torwent**

### CODE REVIEW

**Comment by Torwent** [comment]
To add to the `TRSInventory.ShiftDrop` change, I made the change for 2 reasons:
- it's way cleaner
- I'm kind of assuming that using the internal method is faster which might actually not be the case, I'm just assuming it is. 

Regardless of wether it's faster or not I prefer this just for being cleaner

**Comment by slackydev** [comment]
Yes the Intersection-method should be faster. But since there are a so few items, not by much. 
Thanks for the fixes.

**Comment by Torwent** [comment]
I actually ended up testing both in 10k loops and the `for loop` was consistently faster... but only by half a second on 10k attempts so in reality it's unnoticeable.

Still I prefer the intersection due to being much cleaner.

**Comment by slackydev** [comment]
> I actually ended up testing both in 10k loops and the `for loop` was consistently faster... but only by half a second on 10k attempts so in reality it's unnoticeable.
> 
> Still I prefer the intersection due to being much cleaner.

I see. I suppose up to 28 items is not really enough for it to gain any traction over the O(n^2) method, would be more performant on a bigger samplesize. This is due to the high per element constant cost.

**Pull request merged**
