### PR TITLE
Bug fixes and minor additions

### PR DESCRIPTION
**Pull request by Torwent**

### CODE REVIEW

**Comment by slackydev** [comment]
next please

**Comment by Torwent** [comment]
You did not accept though! but alright!

**Comment by Torwent** [comment]
Forgot to mention in the last commit:
Also added `TRSBank.ContainsItem(item: TRSItem)` and marked the old `TRSBank.FindItem(Item: TRSItem)`with a comment as deprecated! This is also an optional addition but I would like to bring the SRL1400 API and SRL1500 APIs closer together.

Also, since the previous one was not removed, there's no downside aside maybe 1 millisecond more of compile time.

**Comment by Torwent** [comment]
I think we are done for now!
All this new commits are really optional, just bringing SRL1400 and SRL1500 APIs closer together.

If this does not make it for whatever reason it doesn't affect the next things too much other than 1 or 2 walker functions that use MM2MS.

I have in store one unrelated rework and then I'll get to the start of the show.

**Comment by slackydev** [comment]
This has been talked about else where, but just for clarity when looking back:
> `function TRSBank.FindItem(Item: TRSItem): Boolean; overload;`

should use the `depreciated` keyword, which can be extended with a sentence about what has replace it.

> `function TRSBank.FindItem(Item: TRSItem): Boolean; overload; deprecated 'use TRSBank.ContainsItem';`

`MainScreen.ConvertDistance()` should not be removed out of the blue. But instead added as a deprecated method like shown above.

**Comment by slackydev** [comment]
Thank you.

**Pull request merged**
