### PR TITLE
refactor: changed how BioHash is setup

### PR DESCRIPTION
**Pull request by Torwent**
Setting up BioHash is now a method of TRSLoginPlayer and it's automatically setup when TRSLogin.AddPlayer is used.

### CODE REVIEW

**Comment by Torwent** [comment]
I've also updated itemfinder to have the latest items.
used Olly tool for it and all looks alright

**Comment by slackydev** [comment]
I've looked through every commit, and it looks fine to me. I am gonna wait and see if @ollydev has any input.

**Comment by Torwent** [comment]
His argument that `inventory.count()` is slow because the inventory slots are not cached is valid.
We should indeed cache them and we could indeed have more readable code instead of weird color finding even though it would be faster.

I'm guessing he already did the caching on his new reworked interfaces branch and unless this is indeed much much faster having simpler code would be better.

**Comment by slackydev** [comment]
Gonna go ahead and merge this - before it grows to large to comprehend.

**Comment by Torwent** [comment]
My bad, I should have made another branch for this

**Pull request merged**
