### PR TITLE
fix: new simba compatibility

### PR DESCRIPTION
**Pull request by Torwent**
This is a change for a not yet released Simba... But since it will eventually be released I'll leave this PR here.
It's probably better not to accept it until the changes are released so it doesn't break things for anyone that doesn't compile Simba from source

### CODE REVIEW

**Comment by slackydev** [comment]
What commit does this target?

Edit: https://github.com/Villavu/Simba/commit/3da41cefc5cd06fc9142c14c7ef1c38c5bee6374

**Comment by Torwent** [comment]
Yes. I've also added the latest item-finder changes made by @ollydev to fix repeated items with the same sprite.

**Comment by Torwent** [comment]
Since simba builds are automatically stored in [build-archive](https://github.com/Villavu/Simba-Build-Archive) I guess this could now be merged

**Comment by slackydev** [comment]
ty

**Pull request merged**
