### PR TITLE
fix: changed `TRSWalker.GetTileMS` parameters to be vectors

### PR DESCRIPTION
**Pull request by Torwent**
Also removed an unused variable `TRSWalker.AdaptiveWalkCheck`

### CODE REVIEW

**Comment by Torwent** [comment]
Don't accept this yet please... I was reviewing other things I have in WaspLib and I'll probably change this

**Comment by Torwent** [comment]
Okay I'm done with this.

Added a more general use function to get tiles without `Walker`. This is useful for to get MMDot tiles for example, specially when you want to take an NPC Height into account.

And changed the `Walker.GetTileMS()` to call that instead.

`Minimap.PointToMS()` is good to just get a tile but the lack of height makes it fall short for certain situations.

And because I added `Minimap.GetTileMS()`that basically had the same calculations `Walker.GetTileMS()` did, I made it call  `Minimap.GetTileMS()` instead.

**Comment by slackydev** [comment]
Danke schön

**Comment by Torwent** [comment]
Værsågod

**Pull request merged**
